# Generated by Django 4.0.3 on 2022-03-31 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SnapYelp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
