version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/app
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/app
    ports:
      - "8000:8000"
    